#!/bin/bash

GORSEMEN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SEASON3_URL="https://tv.nrk.no/serie/vikingane/sesong/3/episode/1/avspiller"

open -a "Google Chrome" --args \
    --load-extension=$GORSEMEN_DIR/chrome_ext \
    $SEASON3_URL
